url: https://eccelyr.github.io
baseurl: /aces/

# Site settings
title: ACES <img src="img/LOGO.png" style="width: 5%; height: 5%"/>>
email: your-email@domain.com
description: "Aumenta tus posibilidades de salir al mundo sin miedo viviendo la experiencia ACES “ingles inmersivo de supervivencia en la vida real”. Bajo este esquema estarás en capacidad de enfrentarte a conversaciones basadas en la rutina diaria que impliquen el uso de la lengua inglesa en contextos que van desde las expresiones para saludar formal e informalmente, pasando por las formas de comprar o vender en establecimientos comerciales e incluso cómo contar historias o hablar sobre expectativas a futuro todo en el marco de las culturas de los Estados Unidos y/o el Reino Unido. Nuestro enfoque va dirigido a las cuatro competencias básicas de aprendizaje de los idiomas, tales como: listening (escucha) speaking (habla) reading (lectura) y writing (escritura). Todas funcionando en conjunto para una mejor disposición del uso de la lengua en cualquier área laboral o cotidiana. 
https://www.facebook.com/acescolombia/"

# Team names, titles and social links
people:
- name: Andrés Felipe Pérez Martínez

  pic: 
  position:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: DANIEL CELY RODRIGUEZ

  pic: 
  position:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: María Camila Barbosa Gómez

  pic: 
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- name: Sergio Andrés Avellaneda Rodríguez


  pic: 
  position:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- name: Ixel Cegarra

  pic: 
  position:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
